spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    platform: hsqldb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password: